export const SHIPPING_ADDRESS_FAIL = "SHIPPING_ADDRESS_FAIL";
export const SHIPPING_ADDRESS_SUCCESS = "SHIPPING_ADDRESS_SUCCESS";
export const SHIPPING_ADDRESS_REQUEST = "SHIPPING_ADDRESS_REQUEST";

export const SHIPPING_ADDRESS_POST_SUCCESS = "SHIPPING_ADDRESS_POST_SUCCESS";
export const SHIPPING_ADDRESS_POST_FAIL = "SHIPPING_ADDRESS_POST_FAIL";
export const SHIPPING_ADDRESS_POST_REQUEST = "SHIPPING_ADDRESS_POST_REQUEST";

export const ORDER_POST_REQUEST = "ORDER_POST_REQUEST";
export const ORDER_POST_SUCCESS = "ORDER_POST_SUCCESS";
export const ORDER_POST_FAIL = "ORDER_POST_FAIL";

export const ORDER_GET_REQUEST = "ORDER_GET_REQUEST";
export const ORDER_GET_SUCCESS = "ORDER_GET_SUCCESS";
export const ORDER_GET_FAIL = "ORDER_GET_FAIL";

export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";
